Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,6 +84,13 @@ jobs:
         aws ec2 modify-launch-template \
           --launch-template-name ${{ env.TEMPLATE_NAME }} \
           --default-version $NEW_VERSION
+
+    - name: Check appspec.yml
+      run: |
+        if [ ! -f appspec.yml ]; then
+          echo "Error: appspec.yml file not found in the repository root."
+          exit 1
+        fi
       
     - name: Deploy to EC2
       run: |
